import {
  Home,
  CourseInfo,
  ArticleInfo,
  Category,
  Courses,
  Login,
  Register,
  AllArticles,
  ContactUs,
  Search,
  AdminPanel,
  Users,
  P_Courses,
  Menus,
  Articles,
  AdminCategory,
  AdminContact,
  Sessions,
  Comments,
  SessionInfo,
  PAdminPrivate,
  UserPanelIndex,
  UserPanelInnerIndex,
  Orders,
  UserPanelCourses,
  Tickets,
  SendTicket,
  TicketAnswer,
  EditAccount,
  Index,
  Draft,
  Offs,
  AdminTickets,
  Discounts,
} from "./shares";

const routes = [
  { path: "/", element: <Home /> },
  { path: "/course-info/:courseName/:commentsPage", element: <CourseInfo /> },
  { path: "/category-info/:categoryName/:page", element: <Category /> },
  { path: "/article-info/:articleName", element: <ArticleInfo /> },
  { path: "/courses/:page", element: <Courses /> },
  { path: "/articles/:page", element: <AllArticles /> },
  { path: "/login", element: <Login /> },
  { path: "/register", element: <Register /> },
  { path: "/contact-us", element: <ContactUs /> },
  { path: "/search/:value", element: <Search /> },
  { path: "/:courseName/:sessionId", element: <SessionInfo /> },
  {
    path: "/p-admin/*",
    element: (
      <PAdminPrivate>
        <AdminPanel />
      </PAdminPrivate>
    ),
    children: [
      { path: "", element: <Index /> },
      { path: "users", element: <Users /> },
      { path: "courses", element: <P_Courses /> },
      { path: "menus", element: <Menus /> },
      { path: "articles/draft/:shortName", element: <Draft /> },
      { path: "articles", element: <Articles /> },
      { path: "category", element: <AdminCategory /> },
      { path: "contact", element: <AdminContact /> },
      { path: "sessions", element: <Sessions /> },
      { path: "comments", element: <Comments /> },
      { path: "offs", element: <Offs /> },
      { path: "tickets", element: <AdminTickets /> },
      { path: "discounts", element: <Discounts /> },
    ],
  },
  {
    path: "/my-account/*",
    element: <UserPanelIndex />,
    children: [
      { path: "", element: <UserPanelInnerIndex /> },
      { path: "orders", element: <Orders /> },
      { path: "buyed", element: <UserPanelCourses /> },
      { path: "tickets", element: <Tickets /> },
      { path: "send-ticket", element: <SendTicket /> },
      { path: "tickets/answer/:id", element: <TicketAnswer /> },
      { path: "edit-account", element: <EditAccount /> },
    ],
  },
];

export default routes;
